############### ## MONITORS ### ###############

$monitor_name = HDMI-A-1
monitor = $monitor_name, disabled
$monitor_name = DP-1

# monitor = ,preferred,auto,1

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor= $monitor_name,3440x1440@144, 0x0, 1 # Home monitor
# monitor= $monitor_name,3440x1440@60, 0x0, 1 # Home monitor (dummy plug)
# monitor= $monitor_name,3440x1440@100, 0x0, 1 # For USB office remote work
# monitor= $monitor_name,1920x1080@60, 0x0, 1 # For standard 1080 p monitors
# monitor= $monitor_name,1280x720@60, 0x0, 1 # For standard 720 p monitors
# monitor = $monitor_name,2256x1504@60, 0x0, 1 # For Framework laptop
# monitor= $monitor_name,4944x1504@50, 0x0, 1.6 # Houston setup
# monitor= $monitor_name,2400x1080@60, 0x0, 2 # For Google Pixel
