# Hyprland theme configuration file

# GTK 3 dark theme
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"

# GTK 4 dark theme
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
# env = GTK_THEME, Orchis-Dark-Compact

# Dark theme for Qt apps (TODO: Work out why pavucontrol-qt is not dark)
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME
env = QT_QPA_PLATFORM, wayland
env = QT_QPA_PLATFORMTHEME, qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_STYLE_OVERRIDE, kvantum
env = QT_QPA_PLATFORMTHEME, qt6ct
exec = kvantummanager --set KvSimplicityDark

# Cursor theme for GTK apps
exec-once = gsettings set org.gnome.desktop.interface cursor-theme BreezeX-RosePine-Linux

# For apps supporting hyprcursor
env = HYPRCURSOR_SIZE,28
env = HYPRCURSOR_THEME,rose-pine-hyprcursor

# For X11 apps
env = XCURSOR_SIZE,28
env = XCURSOR_THEME,rose-pine-hyprcursor
env = XDG_MENU_PREFIX,arch-
